language: R
sudo: false
cache: packages

r:
  - release
  - devel

notifications:
  email: false

r_packages:
  - covr

after_success:
- Rscript -e 'library(covr); codecov()'

before_install:
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

apt_packages: libudunits2-dev
